name: wefarm
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cron: ^0.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  simple_connection_checker: ^0.2.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/PoppinsBold.ttf
        weight: 700
      - asset: assets/fonts/PoppinsSemiBold.ttf
        weight: 600
      - asset: assets/fonts/PoppinsMedium.ttf
        weight: 500
      - asset: assets/fonts/PoppinsRegular.ttf
        weight: 400
